config/routes.rb
require 'gollum/app'

Io::Application.routes.draw do
  root :to => "home#index"

  resources :trainings, :only => [:index] do
    resources :sessions
    get 'schedule'
  end

  namespace :admin do
    resources :trainings, only: [:index, :update, :create] do
      member do
        get 'schedule', :as => :schedule
        get 'export.:format' => "trainings#export", :as => :export
      end
    end

    resources :users, :only => [:index, :show, :edit] do
      member do
        put 'update_role'
      end
    end

    get 'wiki/pages' => 'wiki#pages'
  end

  get '/apache/vhost' => 'apache#vhost'

  get '/auth/:provider/callback' => 'login#create'
  get '/signin' => 'login#new', :as => :signin
  get '/signout' => 'login#destroy', :as => :signout
  post '/auth/failure' => 'login#failure'

  mount Precious::MyApp, at: 'wiki'
end

app/models/training.rb
class Training < ActiveRecord::Base
  attr_accessible :starts_at, :title, :is_active

  has_many :sessions

  scope :active, -> { where(is_active: true) }

  validates_presence_of :starts_at
end

app/controllers/admin/trainings_controller.rb
require 'csv'

class Admin::TrainingsController < AdminController
  load_and_authorize_resource

  def index
    @trainings = Training.order('starts_at DESC')
  end

  def update
    if @training.update_attributes(params[:training])
      @command = Io::Training::Update.new(training: @training)
      @command.perform

      flash[:success] = "Saved"
      redirect_to admin_trainings_path
    else
      redirect_to admin_trainings_path, notice: 'Error'
    end
  end

  def create
    @training = Training.new(params[:training])

    if @training.save
      redirect_to admin_trainings_path
    else
      redirect_to admin_trainings_path, notice: 'Error'
    end
  end

  def schedule
    @sessions = @training.sessions.order('position ASC')
    @users = User.trainers.order('name ASC')
  end

  def export
    @sessions = @training.sessions.order('position ASC')

    respond_to do |format|
      format.csv { export_csv }
    end
  end

  private

  def export_csv
    filename = I18n.l(Time.now, :format => :short) + "-#{@training.title}.csv"
    content = CSV.generate do |c|
      c << ['Date', 'Session', 'Responsibles']
      @sessions.each do |s|
        c << [s.starts_at, s.title, s.responsibles.collect {|r| r.name}]
      end
    end

    send_data content, :filename => filename
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < AuthenticatedController
  def schedule
    @training = ::Training.find(params[:training_id])
    @presenter = SchedulePresenter.new(current_user)

    schedule = Io::Session::Schedule.new(@training, current_user)
    @sessions = schedule.sessions
  end
end

app/views/trainings/_session.html.haml
%tr{class: presenter.css_class_for_session(session) }
  %td.date= I18n.l(session.starts_at, format: :short_with_weekday_name, day: session.starts_at.day.ordinalize)
  %td.descriptions
    - if session.title.present?
      .line
        %span.title Description:
        %span= session.title
    - if presenter.show_responsibles?(session)
      .line
        %span.title Responsibles
        - session.responsibles.each do |responsible|
          %span.label.responsible #{responsible.name}

    - if session.has_wiki_pages?
      .line
        %span.title Wiki:
        - session.wiki_pages.each do |page|
          %a.wiki_link{href: wiki_page_url(page), target: '_blank'}
            %span.label.label-info= page

app/views/trainings/schedule.html.haml
.row.user_schedule
  .span12
    - if @sessions.any?
      .row
        .span10
          %h2 Training schedule
        - if @presenter.show_edit_link?
          .span2.pull-right{style: "text-align: right;"}
            = link_to "Edit schedule", schedule_admin_training_path(@training)
            %br
            %br
      .row
        .span12
          %table.table.table-bordered.schedule_table
            %thead
              %tr
                %th.date Date
                %th.th-1.th-2.th-3 Topic
            %tbody
              - if @sessions.any?
                - @sessions.each do |session|
                  = render 'session', session: session, presenter: @presenter
    - else
      %h2 Come back on #{I18n.l(@training.starts_at, format: :long_with_weekday_name_summary)}