config/routes.rb
require 'gollum/app'

Io::Application.routes.draw do
  root :to => "home#index"

  resources :trainings, :only => [:index] do
    resources :sessions
    get 'schedule'
  end

  namespace :admin do
    resources :trainings, only: [:index, :update, :create] do
      member do
        get 'schedule', :as => :schedule
        get 'export.:format' => "trainings#export", :as => :export
      end
    end

    resources :users, :only => [:index, :show, :edit] do
      member do
        put 'update_role'
      end
    end

    get 'wiki/pages' => 'wiki#pages'
  end

  get '/apache/vhost' => 'apache#vhost'

  get '/auth/:provider/callback' => 'login#create'
  get '/signin' => 'login#new', :as => :signin
  get '/signout' => 'login#destroy', :as => :signout
  post '/auth/failure' => 'login#failure'

  mount Precious::MyApp, at: 'wiki'
end

app/models/training.rb
class Training < ActiveRecord::Base
  attr_accessible :starts_at, :title, :is_active

  has_many :sessions

  scope :active, -> { where(is_active: true) }

  validates_presence_of :starts_at
end

app/controllers/admin/trainings_controller.rb
require 'csv'

class Admin::TrainingsController < AdminController
  load_and_authorize_resource

  def index
    @trainings = Training.order('starts_at DESC')
  end

  def update
    if @training.update_attributes(params[:training])
      @command = Io::Training::Update.new(training: @training)
      @command.perform

      flash[:success] = "Saved"
      redirect_to admin_trainings_path
    else
      redirect_to admin_trainings_path, notice: 'Error'
    end
  end

  def create
    @training = Training.new(params[:training])

    if @training.save
      redirect_to admin_trainings_path
    else
      redirect_to admin_trainings_path, notice: 'Error'
    end
  end

  def schedule
    @sessions = @training.sessions.order('position ASC')
    @users = User.trainers.order('name ASC')
  end

  def export
    @sessions = @training.sessions.order('position ASC')

    respond_to do |format|
      format.csv { export_csv }
    end
  end

  private

  def export_csv
    filename = I18n.l(Time.now, :format => :short) + "-#{@training.title}.csv"
    content = CSV.generate do |c|
      c << ['Date', 'Session', 'Responsibles']
      @sessions.each do |s|
        c << [s.starts_at, s.title, s.responsibles.collect {|r| r.name}]
      end
    end

    send_data content, :filename => filename
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < AuthenticatedController
  def schedule
    @training = ::Training.find(params[:training_id])
    @presenter = SchedulePresenter.new(current_user)

    schedule = Io::Session::Schedule.new(@training, current_user)
    @sessions = schedule.sessions
  end
end

app/views/admin/trainings/_training.html.haml
.modal{:id => "training-edit-#{training.id}", :style => "display: none;"}
  = simple_form_for training, :url => training.persisted? ? admin_training_path(training) : admin_trainings_path, :html => {:method => training.persisted? ? :put : :post, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3= training.persisted? ? "Edit training" : "New training"
    .modal-body
      = f.input :title
      = f.input :starts_at
      = f.input :is_active
    .modal-footer
      = f.submit "Save", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/admin/trainings/index.html.haml
%h2 Trainings
.row
  .span12
    %table.table.table-bordered
      %thead
        %tr
          %th ID
          %th Title
          %th Starts at
          %th Active
          %th Last updated
          %th.actions
      %tbody
        - @trainings.each do |training|
          %tr
            %td= training.id
            %td= training.title
            %td= training.starts_at
            %td= training.is_active
            %td= l(training.updated_at)
            %td
              %a.btn.btn-mini{"data-toggle" => "modal", :href => "#training-edit-#{training.id}", :type => "button"} Edit
              %a.btn.btn-mini{href: schedule_admin_training_path(training), type: "button"} Schedule
              %a.btn.btn-mini{href: export_admin_training_path(training, format: :csv), type: "button"} Export
              = render training
        %a.btn{"data-toggle" => "modal", :href => "#training-edit-", :type => "button"} New
        = render Training.new

app/views/admin/trainings/schedule.html.haml
%h2.heading Schedule

#schedules

= content_for(:scripts) do
  :coffeescript
    training = new Io.Models.Training(#{@training.to_json.html_safe})
    sessions = #{@sessions.to_json(include: [:responsibles]).html_safe}
    users = #{@users.to_json(include: [:roles])}

    window.router = new Io.Admin.Routers.SchedulesRouter(training: training, sessions: sessions, users: users)

    Backbone.history.start()