config/routes.rb
require 'gollum/app'

Io::Application.routes.draw do
  root :to => "home#index"

  resources :trainings, :only => [:index] do
    resources :sessions
    get 'schedule'
  end

  namespace :admin do
    resources :trainings, only: [:index, :update, :create] do
      member do
        get 'schedule', :as => :schedule
        get 'export.:format' => "trainings#export", :as => :export
      end
    end

    resources :users, :only => [:index, :show, :edit] do
      member do
        put 'update_role'
      end
    end

    get 'wiki/pages' => 'wiki#pages'
  end

  get '/apache/vhost' => 'apache#vhost'

  get '/auth/:provider/callback' => 'login#create'
  get '/signin' => 'login#new', :as => :signin
  get '/signout' => 'login#destroy', :as => :signout
  post '/auth/failure' => 'login#failure'

  mount Precious::MyApp, at: 'wiki'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  attr_accessible :provider, :uid, :name, :email
  attr_accessible :provider, :uid, :name, :email, :role_ids, :as => :admin

  has_many :sessions

  scope :trainers, -> { with_role('trainer') }

  def accessible_by
    [User.first]
  end

  def author_info
    { name: name, email: email }
  end

  # ============
  # Ability
  # ============

  def ability
    @ability ||= Ability.new(self)
  end

  def username
    email[/(^.*)@/, 1]
  end

  def member_of_staff?
    has_role?(:trainer) || has_role?(:staff)
  end

  delegate :can?, :cannot?, :to => :ability
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def update_role
    @user = User.find(params[:id])
    authorize! :change_role, @user

    if @user.update_attributes(params[:user], as: :admin)
      flash[:success] = "Updated #{@user.name}"
      redirect_to admin_users_path
    else
      redirect_to admin_users_path, notice: "Failed"
    end
  end
end

app/views/admin/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => update_role_admin_user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :check_boxes, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline'
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/admin/users/index.html.haml
%h2 Users
.row
  .span12
    %table.table.table-bordered
      %thead
        %tr
          %th Username
          %th Email
          %th Registered
          %th Role
          %th
          -#%th
      %tbody
        - @users.each do |user|
          %tr
            %td= user.name
            %td= user.email
            %td= user.created_at.to_date
            %td= user.roles.first.name.titleize unless user.roles.first.nil?
            %td
              %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
              = render user
            -#%td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user