config/routes.rb
require 'gollum/app'

Io::Application.routes.draw do
  root :to => "home#index"

  resources :trainings, :only => [:index] do
    resources :sessions
    get 'schedule'
  end

  namespace :admin do
    resources :trainings, only: [:index, :update, :create] do
      member do
        get 'schedule', :as => :schedule
        get 'export.:format' => "trainings#export", :as => :export
      end
    end

    resources :users, :only => [:index, :show, :edit] do
      member do
        put 'update_role'
      end
    end

    get 'wiki/pages' => 'wiki#pages'
  end

  get '/apache/vhost' => 'apache#vhost'

  get '/auth/:provider/callback' => 'login#create'
  get '/signin' => 'login#new', :as => :signin
  get '/signout' => 'login#destroy', :as => :signout
  post '/auth/failure' => 'login#failure'

  mount Precious::MyApp, at: 'wiki'
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%button.btn.btn-navbar{'data-toggle' => "collapse", 'data-target' => '.nav-collapse'}
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar

= link_to "Io", root_path, :class => 'brand'
.nav-collapse
  - if user_signed_in?
    %ul.nav{class: 'pull-right'}
      %li
        = link_to "Logout - #{current_user.name}", signout_path
  %ul.nav
    - if !user_signed_in?
      %li
        = link_to 'Login', signin_path
    - if user_signed_in?
      %li
        = link_to 'Wiki', '/wiki'
      %li
      - if current_user.member_of_staff?
        %li.dropdown
          %a.dropdown-toggle{ data: { toggle: "dropdown" } } Admin
          %ul.dropdown-menu
            - if current_user.can? :manage, User
              %li
                = link_to 'Users', admin_users_path
            - if current_user.can? :manage, Training
              %li
                = link_to 'Trainings', admin_trainings_path
      - if Training.active.any?
        %li
          = link_to 'Schedule', training_schedule_path(Training.active.last)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Io"
    %meta{:content => content_for?(:description) ? yield(:description) : "Io", :name => "description"}
    = stylesheet_link_tag "application", :media => "all"
    %link{:href => "https://fonts.googleapis.com/css?family=Limelight|Flamenco|Federo|Yesteryear|Josefin Sans|Spinnaker|Sansita One|Handlee|Droid Sans|Oswald:400,300,700", :media => "screen", :rel => "stylesheet", :type => "text/css"}
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    = airbrake_javascript_notifier
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container-fluid
          = render 'layouts/navigation'
    #container.container.content
      = render 'layouts/messages'
      = yield
    %footer
      / ! end of .container
    / ! end of #main
    = javascript_include_tag "application"
    = yield :scripts